version: "1.0"

services:
    mariadb:
        image: mariadb:10.6
        restart: unless-stopped
        ports:
            - 3306:3306
        env_file:
            dev.env
        volumes:
            - db:/var/lib/mariadb
    
    api:
        depends_on:
            - mariadb
        build: ./api
        restart: unless-stopped
        env_file:
            dev.env
        ports:
            - "8080:8080"

volumes:
    db: